/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Post = {
  _id: string;
  _type: "post";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  generationError?: string;
  regenerationKey?: string;
  topic?: string;
  factText?: string;
  source?: {
    citation?: string;
    url?: string;
  };
  caption?: string;
  renderTemplate?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  status?: "generating" | "inReview" | "approved" | "published";
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | Post
  | SanityImageCrop
  | SanityImageHotspot
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint
  | Slug;

// Source: ../web/src/sanity/posts.ts
// Variable: postsQuery
// Query: *[_type == "post"] | order(_updatedAt desc){_id, _updatedAt, topic, factText, caption, source{citation, url}, status, renderTemplate, generationError,  "image": image.asset->{url, mimeType, "width": metadata.dimensions.width, "height": metadata.dimensions.height}}
export type PostsQueryResult = Array<{
  _id: string;
  _updatedAt: string;
  topic: string | null;
  factText: string | null;
  caption: string | null;
  source: {
    citation: string | null;
    url: string | null;
  } | null;
  status: "approved" | "generating" | "inReview" | "published" | null;
  renderTemplate: string | null;
  generationError: string | null;
  image: {
    url: string | null;
    mimeType: string | null;
    width: number | null;
    height: number | null;
  } | null;
}>;

// Source: ../web/src/sanity/posts.ts
// Variable: postQuery
// Query: *[_type == "post" && _id == $id][0]{_id, _updatedAt, topic, factText, caption, source{citation, url}, status, renderTemplate, generationError,  "image": image.asset->{url, mimeType, "width": metadata.dimensions.width, "height": metadata.dimensions.height}}
export type PostQueryResult = {
  _id: string;
  _updatedAt: string;
  topic: string | null;
  factText: string | null;
  caption: string | null;
  source: {
    citation: string | null;
    url: string | null;
  } | null;
  status: "approved" | "generating" | "inReview" | "published" | null;
  renderTemplate: string | null;
  generationError: string | null;
  image: {
    url: string | null;
    mimeType: string | null;
    width: number | null;
    height: number | null;
  } | null;
} | null;

// Query TypeMap
declare global {
  interface SanityQueries {
    '*[_type == "post"] | order(_updatedAt desc){_id, _updatedAt, topic, factText, caption, source{citation, url}, status, renderTemplate, generationError,\n  "image": image.asset->{url, mimeType, "width": metadata.dimensions.width, "height": metadata.dimensions.height}}': PostsQueryResult;
    '*[_type == "post" && _id == $id][0]{_id, _updatedAt, topic, factText, caption, source{citation, url}, status, renderTemplate, generationError,\n  "image": image.asset->{url, mimeType, "width": metadata.dimensions.width, "height": metadata.dimensions.height}}': PostQueryResult;
  }
}
// Lets @sanity/client releases that predate the global registry read it too
declare module "@sanity/client" {
  interface SanityQueries extends globalThis.SanityQueries {}
}
